### PR TITLE
Add jsconfig.json to root of project to enable ES6 support VSC

### PR DESCRIPTION
**Pull request by intabulas**
I added this yesterday when I sent it to @schahriar and forgot to push it as a PR

Add jsconfig.json to root of project to enable ES6 support in Visual Studio Code

### CODE REVIEW

**Comment by keithwhor** [comment]
Going to request that this doesn't pollute the root directory. If a user wants a VSC project they should specify something like a `--vsc` flag on `nodel new` and then we can create this.

**Comment by intabulas** [comment]
Yeah okay I can change it to that

**Comment by intabulas** [comment]
One comment though. I did this in the root of nodal for nodal dev vs nodal apps. I would think a --vsc on a `nodal new` would add it to the generated app

**Comment by schahriar** [comment]
@intabulas VSCode strictly requires `"esnext": true` for work with ES6 (I have no idea why it is so stubborn). I think the config can change over time and might not be relevant to the project so we might as well just add a one-liner to `.gitignore` and have the dev add it on their own.

**Comment by keithwhor** [comment]
@intabulas Oh true, didn't see what directory you had added it to... I think we can probably roll with that.

**Comment by keithwhor** [comment]
Any reason tabs are used here? Can we switch to 2 spaces instead?

**Comment by intabulas** [comment]
I need to fix that.. It was a copy of a file

**Pull request merged**
