### PR TITLE
Daemon v2

### PR DESCRIPTION
**Pull request by schahriar**
New version of `core/required/daemon` that relies on **Clusters** instead of `uncaughtException`.

Features:
- Automatic restore
- Much better process cleanup
- Exception/Error handling
- `uncaughtException` within a Worker to report errors right before death
- Ability for automatic future clustering of Nodal applications
- Master/Worker communication layer with graceful kill
- Worker ID without collisions (multiple instances of Daemon can be created in one script)

Issues:
- Worker is likely to get killed before graceful death.

This is a work in progress and although it does work in its current form it is **breaking** and includes **a few bugs**.

### CODE REVIEW

**Comment by keithwhor** [comment]
This is hugely breaking. Can you do a squash commit so I can see everything changing at once? Lot of single liners here.

**Comment by schahriar** [comment]
@keithwhor Since this is a part of 0.7 now I think you should create an internal branch and I'll squash the commits and push them there so we can easily compare conflicts in the future. I'll also be able to PR changes to that specific branch and discuss them rather than making one passive PR at the end .

**Comment by keithwhor** [comment]
@schahriar Will do.

**Comment by schahriar** [comment]
@keithwhor I am gonna close this for now. Once we start working on 0.7 I'll make a PR for the 0.7 branch.

**Pull request closed without merging**
