### PR TITLE
Making it work with Babel

### PR DESCRIPTION
**Pull request by seivan**
This still needs some extra work. Especially some of the changes I've made (not proud). Maybe you could look into it or share how you currently run the dev environment?

### CODE REVIEW

**Comment by seivan** [comment]
I am not expecting this to be accepted, just trying to figure out how to get it to run the test suite on my end. Babel had some issues with assignment in if statements, so I changed those. Obviously that broke the test.  Would love some input here.

**Comment by keithwhor** [comment]
I think I'm a bit confused --- why are you trying to get this to work with Babel?

**Comment by intabulas** [comment]
@seivan just clone the repo (or fork and clone) then do an npm i and an npm test works just fine for me. As far as dev using a local clone, what I have done is rm the node_modules/nodal in my generated app and then sym link in my cloned tree in its place. Then I can hack on my clone and test it with an app

**Comment by seivan** [comment]
@keithwhor Because npm install and npm test didn't quite work. How did you use ES6 features without babel?

**Comment by intabulas** [comment]
What version of node are you running on?

**Comment by keithwhor** [comment]
Node 4.2.4. Get it from http://nodejs.org.

**Pull request closed without merging**
