### PR TITLE
Uses cross-spawn-async for Windows compatibility

### PR DESCRIPTION
**Pull request by IrregularShed**
Replaced `child_process.spawn` with `cross-spawn-async` for cross-platform
compatibility. (Windows command line has problems with
`child_process.spawn`.)

### CODE REVIEW

**Comment by keithwhor** [comment]
Can you write tests for this? I'd like confirmation that this works on all environments, because I haven't spun up a VM with Windows myself. We can test on more environments on TravisCI.

**Comment by keithwhor** [comment]
Great work and thank you very much, btw :)

**Comment by IrregularShed** [comment]
:+1: I'll try and get proper tests written over the weekend (unexpectedly busy afternoon in the office, otherwise I'd have had a go already). So far the testing has been "does this work on my Windows machine" (it does) and Travis giving the thumbs up :)

**Comment by IrregularShed** [comment]
(Travis testing on non-Windows boxes I mean by that)

**Comment by keithwhor** [comment]
Thanks so much! Understand the busy office situation. Same here. ;)

**Comment by schahriar** [comment]
@keithwhor considering that you can't run Windows tests on Travis do you plan to intergrate something like [appveyor](https://www.appveyor.com/) for the tests? I can write the test (depending on what you would expect) as I am in dire need for this PR to be merged so I can develop on my Windows setup.

**Comment by IrregularShed** [comment]
Tests are going to be hard to achieve for a while - I'm having an absolute nightmare getting the tests to start on Windows. Adjusting the `child_process.execSync()` commands in `runner.js` so that `\'` are replaced with `"` was enough to get the postgres commands to at least run, but the command for creating the database fails completely when I try and call it from within Node (either in the test script or directly from the REPL) - the process shudders to a halt and remains unresponsive.

**Comment by keithwhor** [comment]
Hey, if you guys are confident this works as intended I have no problem merging at this point. If tests are a nightmare let's just not worry about it.

**Comment by schahriar** [comment]
That sounds awful :( I might give it a go today and see what I can do. Is this only applicable to runner.js? `psql -c \'create database nodal_test;\' -U postgres` I think this is the command you are referring to. @keithwhor I haven't tested the PR so don't take my word for it. I believe we should test this properly before leaving the chance for crashing the entire ecosystem (since we rely on child_process to do db stuff)

**Comment by schahriar** [comment]
@keithwhor are you working on an db adapter system like sails' waterline or sticking with SQL for now? Because we could re-write this in the new CLI changes.

**Comment by keithwhor** [comment]
@schahriar We have a built in db adapter system, not sure what you're asking?

**Comment by schahriar** [comment]
@keithwhor I was referring to support for other databases (MySQL, Mongo, etc.) but nvm I confused runner.js with the rest of the code forgetting that it was part of the test. `cli.js` seems to use `./db/commands.js` which is what I was looking for.

**Comment by schahriar** [comment]
@IrregularShed I got `runner.js` working and from what I see this is mostly because of `psql` response speed. Add me as a collaborator so I can push the changes to this PR.

**Comment by IrregularShed** [comment]
@schahriar You're added :)

**Comment by schahriar** [comment]
@IrregularShed everything seems to be good to go except when password is forced on the user (I think using the -W option) this causes the tests to crash since you don't seem to be able to set it anywhere outside `test/config/db.json`. @keithwhor do you know anyway I can override `core/required/my/config.js` settings just for the tests? This way I can prompt the user for their password once at the start of the test and override it throughout the suite (`psql` password prompt is not working at all on Windows so we have to force it using env and a bunch of options) **Note that this is not specific to this issue but I believe falls under Windows compatibility problem.** Of course if you set your role without a password or a prompt it should work.

**Comment by schahriar** [comment]
Seems like fixes for Windows are breaking everything else. I'll setup a bunch of test servers to test the latest commit before pushing it to the CI.

**Comment by keithwhor** [comment]
Looks good to me. Ran fine.

**Pull request merged**
